import { collection, addDoc, getDocs, limit, query } from 'firebase/firestore';
import { db } from './firebase';

const DEMO_EVENTS = [
  {
    nomeEvento: 'Sarau na Praça Central',
    descricaoCurta: 'Encontro de poetas, músicos e artistas locais na praça principal com microfone aberto e apresentações ao vivo.',
    cidade: 'Montezuma',
    estado: 'MG',
    bairro: 'Centro',
    localEvento: 'Praça Dr. Paulo Boschi',
    dataEvento: '2026-09-10',
    horaEvento: '18:00',
    preco: 'gratuito',
    categoria: 'Literatura',
    acessivel: true,
    recursosAcessibilidade: ['Rampa de acesso', 'Banheiro acessível'],
    status: 'publicado',
    demonstracao: true,
    criadoEm: Date.now(),
    atualizadoEm: Date.now(),
  },
  {
    nomeEvento: 'Oficina de Pintura em Tela',
    descricaoCurta: 'Aprenda técnicas de pintura com artistas da região. Material incluso para todos os participantes.',
    cidade: 'Montezuma',
    estado: 'MG',
    bairro: 'Centro',
    localEvento: 'Casa da Cultura',
    dataEvento: '2026-09-15',
    horaEvento: '14:00',
    preco: 'pago',
    valorIngresso: 'R$ 20,00',
    categoria: 'Artes visuais',
    acessivel: false,
    recursosAcessibilidade: [],
    status: 'publicado',
    demonstracao: true,
    criadoEm: Date.now(),
    atualizadoEm: Date.now(),
  },
  {
    nomeEvento: 'Roda de Samba no Bar do Zé',
    descricaoCurta: 'Samba de raiz com músicos locais, trazendo os grandes clássicos e composições inéditas da região.',
    cidade: 'Montezuma',
    estado: 'MG',
    bairro: 'Centro',
    localEvento: 'Bar do Zé',
    dataEvento: '2026-09-12',
    horaEvento: '20:00',
    preco: 'pago',
    valorIngresso: 'R$ 10,00',
    categoria: 'Música',
    acessivel: true,
    recursosAcessibilidade: ['Banheiro acessível'],
    status: 'publicado',
    demonstracao: true,
    criadoEm: Date.now(),
    atualizadoEm: Date.now(),
  },
  {
    nomeEvento: 'Feira de Artesanato Local',
    descricaoCurta: 'Exposição e venda de artesanato regional, com participação de artesãos da comunidade montezubense.',
    cidade: 'Montezuma',
    estado: 'MG',
    bairro: 'Feira',
    localEvento: 'Praça da Feira',
    dataEvento: '2026-09-20',
    horaEvento: '09:00',
    preco: 'gratuito',
    categoria: 'Feira cultural',
    acessivel: true,
    recursosAcessibilidade: ['Rampa de acesso'],
    status: 'publicado',
    demonstracao: true,
    criadoEm: Date.now(),
    atualizadoEm: Date.now(),
  },
  {
    nomeEvento: 'Peça Teatral: O Auto da Compadecida',
    descricaoCurta: 'Apresentação da clássica obra de Ariano Suassuna pelo grupo de teatro amador da comunidade.',
    cidade: 'Montezuma',
    estado: 'MG',
    bairro: 'Centro',
    localEvento: 'Casa da Cultura',
    dataEvento: '2026-09-25',
    horaEvento: '19:30',
    preco: 'pago',
    valorIngresso: 'R$ 8,00',
    categoria: 'Teatro',
    acessivel: true,
    recursosAcessibilidade: ['Rampa de acesso', 'Banheiro acessível'],
    status: 'publicado',
    demonstracao: true,
    criadoEm: Date.now(),
    atualizadoEm: Date.now(),
  },
  {
    nomeEvento: 'Encontro de Rap e Hip Hop',
    descricaoCurta: 'Encontro de MCs para batalhas de rimas e apresentações de artistas locais. Inscrições abertas na hora.',
    cidade: 'Montezuma',
    estado: 'MG',
    bairro: 'Centro',
    localEvento: 'Praça Dr. Paulo Boschi',
    dataEvento: '2026-09-18',
    horaEvento: '20:00',
    preco: 'gratuito',
    categoria: 'Cultura popular',
    acessivel: false,
    recursosAcessibilidade: [],
    status: 'publicado',
    demonstracao: true,
    criadoEm: Date.now(),
    atualizadoEm: Date.now(),
  },
  {
    nomeEvento: 'Cinema ao Ar Livre: Curtas Mineiros',
    descricaoCurta: 'Exibição de curtas-metragens produzidos em Minas Gerais, seguido de roda de conversa com realizadores.',
    cidade: 'Montezuma',
    estado: 'MG',
    bairro: 'Centro',
    localEvento: 'Praça Dr. Paulo Boschi',
    dataEvento: '2026-09-22',
    horaEvento: '18:30',
    preco: 'gratuito',
    categoria: 'Cinema',
    acessivel: true,
    recursosAcessibilidade: ['Audiodescrição', 'Rampa de acesso'],
    status: 'publicado',
    demonstracao: true,
    criadoEm: Date.now(),
    atualizadoEm: Date.now(),
  },
  {
    nomeEvento: 'Oficina de Dança de Salão',
    descricaoCurta: 'Venha aprender os passos básicos de forró e sertanejo com instrutores da região.',
    cidade: 'Montezuma',
    estado: 'MG',
    bairro: 'Centro',
    localEvento: 'Casa da Cultura',
    dataEvento: '2026-09-28',
    horaEvento: '15:00',
    preco: 'pago',
    valorIngresso: 'R$ 15,00',
    categoria: 'Dança',
    acessivel: false,
    recursosAcessibilidade: [],
    status: 'publicado',
    demonstracao: true,
    criadoEm: Date.now(),
    atualizadoEm: Date.now(),
  }
];

export async function seedDemoEvents() {
  const q = query(collection(db, 'events'), limit(1));
  const snapshot = await getDocs(q);

  if (snapshot.empty) {
    console.log('Seeding demo events...');
    for (const event of DEMO_EVENTS) {
      await addDoc(collection(db, 'events'), event);
    }
    console.log('Seed completo!');
  }
}
